import { Address } from '@/types';

export const mockAddresses: Address[] = [
  {
    id: '1',
    name: 'PT. Teknologi Maju Indonesia',
    address: 'Jl. Sudirman No. 123, Jakarta Selatan',
    phoneNumber: '+6281234567890',
    rating: 4.8,
    reviews: 156,
    website: 'https://tekno-maju.co.id',
    email: 'info@tekno-maju.co.id',
    latitude: -6.2088,
    longitude: 106.8456,
    postalCode: '12190',
    city: 'Jakarta Selatan',
    state: 'DKI Jakarta',
    country: 'Indonesia',
    url: 'https://maps.google.com/123',
    odp: null,
    distance: null,
    status: 'VIP Customer',
    isBusiness: true,
    businessName: 'PT. Teknologi Maju Indonesia',
    businessCategory: 'Teknologi Informasi',
    hasReceivedMessage: true,
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-09-15T14:20:00Z'
  },
  {
    id: '2',
    name: 'Sari Dewi Lestari',
    address: 'Jl. Raya Bandung No. 456, Bandung',
    phoneNumber: '+6281987654321',
    rating: 4.2,
    reviews: 89,
    website: null,
    email: 'sari.dewi@email.com',
    latitude: -6.9175,
    longitude: 107.6191,
    postalCode: '40123',
    city: 'Bandung',
    state: 'Jawa Barat',
    country: 'Indonesia',
    url: null,
    odp: null,
    distance: null,
    status: 'Lead',
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    hasReceivedMessage: false,
    createdAt: '2024-02-20T09:15:00Z',
    updatedAt: '2024-09-10T11:45:00Z'
  },
  {
    id: '3',
    name: 'CV. Berkah Jaya Mandiri',
    address: 'Jl. Ahmad Yani No. 789, Surabaya',
    phoneNumber: '+6281122334455',
    rating: 4.5,
    reviews: 234,
    website: 'https://berkahjaya.com',
    email: 'admin@berkahjaya.com',
    latitude: -7.2575,
    longitude: 112.7521,
    postalCode: '60231',
    city: 'Surabaya',
    state: 'Jawa Timur',
    country: 'Indonesia',
    url: 'https://maps.google.com/456',
    odp: null,
    distance: null,
    status: 'Customer',
    isBusiness: true,
    businessName: 'CV. Berkah Jaya Mandiri',
    businessCategory: 'Perdagangan',
    hasReceivedMessage: true,
    createdAt: '2024-01-10T08:20:00Z',
    updatedAt: '2024-09-12T16:30:00Z'
  },
  {
    id: '4',
    name: 'Ahmad Rizki Pratama',
    address: 'Jl. Diponegoro No. 321, Yogyakarta',
    phoneNumber: '+6281555666777',
    rating: 3.8,
    reviews: 45,
    website: null,
    email: 'ahmad.rizki@gmail.com',
    latitude: -7.7956,
    longitude: 110.3695,
    postalCode: '55224',
    city: 'Yogyakarta',
    state: 'DI Yogyakarta',
    country: 'Indonesia',
    url: null,
    odp: null,
    distance: null,
    status: 'Prospect',
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    hasReceivedMessage: false,
    createdAt: '2024-03-05T13:45:00Z',
    updatedAt: '2024-09-08T10:15:00Z'
  },
  {
    id: '5',
    name: 'Toko Elektronik Maju Bersama',
    address: 'Jl. Veteran No. 654, Medan',
    phoneNumber: '+6281999888777',
    rating: 4.6,
    reviews: 178,
    website: 'https://elektronik-majubersama.id',
    email: 'contact@majubersama.id',
    latitude: 3.5952,
    longitude: 98.6722,
    postalCode: '20111',
    city: 'Medan',
    state: 'Sumatera Utara',
    country: 'Indonesia',
    url: 'https://maps.google.com/789',
    odp: null,
    distance: null,
    status: 'VIP Customer',
    isBusiness: true,
    businessName: 'Toko Elektronik Maju Bersama',
    businessCategory: 'Elektronik',
    hasReceivedMessage: true,
    createdAt: '2024-01-22T11:10:00Z',
    updatedAt: '2024-09-14T09:25:00Z'
  },
  {
    id: '6',
    name: 'Maya Sari Putri',
    address: 'Jl. Gatot Subroto No. 987, Denpasar',
    phoneNumber: '+6281777444111',
    rating: 4.1,
    reviews: 67,
    website: null,
    email: 'maya.sari@yahoo.com',
    latitude: -8.6705,
    longitude: 115.2126,
    postalCode: '80234',
    city: 'Denpasar',
    state: 'Bali',
    country: 'Indonesia',
    url: null,
    odp: null,
    distance: null,
    status: 'Customer',
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    hasReceivedMessage: true,
    createdAt: '2024-02-14T15:20:00Z',
    updatedAt: '2024-09-11T12:40:00Z'
  },
  {
    id: '7',
    name: 'PT. Konstruksi Nusantara Sejahtera',
    address: 'Jl. Pemuda No. 159, Semarang',
    phoneNumber: '+6281333222111',
    rating: 4.4,
    reviews: 92,
    website: 'https://konstruksi-nusantara.co.id',
    email: 'info@konstruksi-nusantara.co.id',
    latitude: -6.9667,
    longitude: 110.4167,
    postalCode: '50132',
    city: 'Semarang',
    state: 'Jawa Tengah',
    country: 'Indonesia',
    url: 'https://maps.google.com/012',
    odp: null,
    distance: null,
    status: 'Lead',
    isBusiness: true,
    businessName: 'PT. Konstruksi Nusantara Sejahtera',
    businessCategory: 'Konstruksi',
    hasReceivedMessage: false,
    createdAt: '2024-03-01T07:30:00Z',
    updatedAt: '2024-09-09T14:55:00Z'
  },
  {
    id: '8',
    name: 'Budi Santoso',
    address: 'Jl. Kartini No. 753, Malang',
    phoneNumber: '+6281666555444',
    rating: 3.9,
    reviews: 23,
    website: null,
    email: 'budi.santoso@hotmail.com',
    latitude: -7.9666,
    longitude: 112.6326,
    postalCode: '65145',
    city: 'Malang',
    state: 'Jawa Timur',
    country: 'Indonesia',
    url: null,
    odp: null,
    distance: null,
    status: 'Prospect',
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    hasReceivedMessage: false,
    createdAt: '2024-02-28T16:45:00Z',
    updatedAt: '2024-09-07T08:20:00Z'
  }
];